language: objective-c

services:
  - mongodb
  - redis-server

env:
  global:
    - EnableNuGetPackageRestore=true 
  matrix:
    - MONO_VERSION="3.2.6"

before_install:
  - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
  - bin/travis_packages.sh
  - bin/travis_build.sh /property:Configuration=Debug ToolBelt.sln
  - bin/travis_build.sh /property:Configuration=Release ToolBelt.sln
  - bin/travis_test.sh Tests/ToolBelt.Tests/bin/Debug/ToolBelt.Tests.dll
  - bin/travis_test.sh Tests/ToolBelt.Tests/bin/Release/ToolBelt.Tests.dll
  - bin/travis_test.sh Tests/ServiceBelt.Tests/bin/Debug/ServiceBelt.Tests.dll
  - bin/travis_test.sh Tests/ServiceBelt.Tests/bin/Release/ServiceBelt.Tests.dll
