language: csharp

mono:
  - latest

solution: ToolBelt.sln

services:
  - mongodb
  - redis-server

env:
  global:
    - EnableNuGetPackageRestore=true 

install:
  - nuget restore ToolBelt.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory packages

script:
  - xbuild /p:Configuration=Debug ToolBelt.sln
  - xbuild /p:Configuration=Release ToolBelt.sln
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tests/ToolBelt.Tests/bin/Debug/ToolBelt.Tests.dll
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tests/ToolBelt.Tests/bin/Release/ToolBelt.Tests.dll
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tests/ServiceBelt.Tests/bin/Debug/ServiceBelt.Tests.dll
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tests/ServiceBelt.Tests/bin/Release/ServiceBelt.Tests.dll
